- name: Setup Ceph Core Dependencies
  hosts: ceph
  roles:
    - { role: ../roles/ceph/dependencies, become: true }
- name: Hosts Maintenance
  hosts: admin[0]
  roles:
    - { role: ../roles/ceph/hosts_maintenance, become: true }